'use strict';
const width = 8;
const height = 4;
const area = width * height; // result = 32
console.log('value of area:', area);
console.log('typeof area:', typeof area);
const bill = 79;
const payment = 27;
const change = bill - payment;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 9;
const midterm = 8;
const final = 7;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Jorge';
const lastName = 'Diaz Martinez';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 6;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 150;
const isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
const motto = fullName + ' ' + 'is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
